### ISSUE TITLE
Changelog reconcile for 0.17.3

### ISSUE THREAD

**Issue by erendrake** [KSP-KOS/KOS#1076]
We have 226 changesets since 0.17.2. We should make sure they are all accounted for in the changelog

- [x] Chris Woerz - update postbuild
- [x] Chris Woerz - Merge remote-tracking branch 'ziwkerman/patch-1' into develop
- [x] Chris Woerz - changes for #1059
- [x] Chris Woerz - Merge remote-tracking branch 'hvacengi/issue-1025-print-engine-list' into develop
- [x] Chris Woerz - changes for #1054
- [x] Chris Woerz - Merge remote-tracking branch 'hvacengi/fix-boot-archive' into develop
- [x] Chris Woerz - Merge remote-tracking branch 'Dunbaratu/Fixes_1048_unlock_works_in_nested_scope' into develop
- [x] Chris Woerz - removed unneeded folder
- [x] Chris Woerz - Merge remote-tracking branch 'Dunbaratu/better_terminal_sound_files' into develop
- [x] Chris Woerz - fixes #1062
- [x] Stepan Andreev - Another typo
- [x] hvacengi - Simplify engine listing
- [x] Brad White - Documentation
- [x] Brad White - Codemaid cleanup
- [x] Brad White - Change the flow of boot
- [x] hvacengi - Enable boot files on archive
- [x] Dunbaratu - Fixes #1048 by making UNLOCK work from nested scope.
- [x] Dunbaratu - Changed the sounds, and added their sources to git.
- [x] Chris Woerz - restored the rest
- [x] Chris Woerz - restore merge messup
- [x] Chris Woerz - review
- [x] Chris Woerz - Merge remote-tracking branch 'abenkovskii/virtual_file_system_fix' into develop
- [x] Chris Woerz - Merge remote-tracking branch 'evg-zhabotinsky/issue1023-doc' into develop
- [x] Chris Woerz - merge
- [x] Chris Woerz - Merge remote-tracking branch 'Dunbaratu/resolves_1042_more_sounds' into develop
- [x] Chris Woerz - review
- [x] Chris Woerz - Merge remote-tracking branch 'Dunbaratu/fixes_1036_gui_terminal_beepable' into develop
- [x] Chris Woerz - Merge remote-tracking branch 'Dunbaratu/short_circuit_and_and_or' into develop
- [x] Chris Woerz - Merge remote-tracking branch 'yump/copy-dlls' into develop
- [x] Chris Woerz - review comments
- [x] Chris Woerz - Merge remote-tracking branch 'hvacengi/issue1029-warpto' into develop
- [x] Chris Woerz - review comments
- [x] Chris Woerz - Merge remote-tracking branch 'abenkovskii/kOS_pannel_investigation' into develop
- [x] abenkovskii - file system fix #1 [fix]
- [x] abenkovskii - file system fix #0 [raw]
- [x] Dunbaratu - Resolves #1042 with a few new clips and sound mgr
- [x] Steven Mading - Merge pull request #1039 from erendrake/develop
- [x] Dunbaratu - missing apostrophe in docs
- [x] Dunbaratu - Fix suffix name in docs (REVERSESCREEM -> REVERSE)
- [x] Dunbaratu - Fixes #1036 with gui terminal beeping and more.
- [x] Evgeniy Zhabotinsky - Documented fact that raw controls are locked separately
- [x] Chris Woerz - Resolves #1023
- [x] Dunbaratu - Removed undocumented math operators on Booleans.
- [x] Evgeniy Zhabotinsky - Fixed TimeWarp as per #989
- [x] Russell Haley - cleanup
- [x] Russell Haley - Improve developer documentation
- [x] Dunbaratu - Boolean AND and OR operations now are short-circuiting.
- [x] Russell Haley - Prevent Linux build from failing if KSPdirlink doesn't exist
- [x] yump - Implement Dunbaratu's outbound symlink idea
- [x] yump - Prevent build failure when files are locked on Windows
- [x] Brad White - Disable maximum and minimum, add documentation
- [x] Russell Haley - Delete PluginData as part of release procedure
- [x] Chris Woerz - adding another test
- [x] Chris Woerz - work on nuget references
- [x] Chris Woerz - minor review
- [x] Chris Woerz - Merge remote-tracking branch 'Dunbaratu/adds_from_loop' into develop
- [x] Chris Woerz - Merge remote-tracking branch 'abenkovskii/round_refactor' into 1030_review
- [x] Brad White - Codemaid cleanup
- [x] Brad White - Argument count
- [x] Chris Woerz - more review changes
- [x] Brad White - Merge branch 'enhance_arg_exception' of https://github.com/erendrake/KOS into issue1029-warpto
- [x] Chris Woerz - Merge branch 'enhance_arg_exception' into 1030_review
- [x] Chris Woerz - fixes
- [x] Chris Woerz - review for #1030
- [x] Chris Woerz - Merge branch 'enhance_arg_exception' into 1030_review
- [x] abenkovskii - Added TODO comment
- [x] abenkovskii - Fixed syntax error
- [x] abenkovskii - Round is now one function not two
- [x] Chris Woerz - enhanced KOSArgumentMismatchException
- [x] Brad White - Codemaid cleanup
- [x] Brad White - Revise engine list logic
- [x] Chris Woerz - Merge remote-tracking branch 'abenkovskii/test_scripts_update' into develop
- [x] Chris Woerz - Merge remote-tracking branch 'abenkovskii/body_soiradius_documentation' into develop
- [x] Brad White - Implement warpto - first draft
- [x] abenkovskii - Added TODO comment
- [x] abenkovskii - fixed testlibpid
- [x] abenkovskii - Fixed syntax error
- [x] abenkovskii - Round is now one function not two
- [x] Russell Haley - Ignore build products and persistent config file
- [x] Dunbaratu - Edited docs to show the new FROM loop.
- [x] ÐÐ½Ð´Ñ€ÐµÐ¹ Ð‘ÐµÐ½ÑŒÐºÐ¾Ð²ÑÐºÐ¸Ð¹ - Merge pull request #16 from KSP-KOS/develop
- [x] Bert Cotton - copying travis from master
- [x] Russell Haley - Add post-build events to copy the dlls into the plugin directory
- [x] abenkovskii - Used the wrong method
- [x] abenkovskii - Fixed stupid errors
- [x] abenkovskii - kOS toolbar panel fix #?unknown_index?
- [x] abenkovskii - Added RectExtensions.cs
- [x] abenkovskii - merge conflict fix
- [x] ÐÐ½Ð´Ñ€ÐµÐ¹ Ð‘ÐµÐ½ÑŒÐºÐ¾Ð²ÑÐºÐ¸Ð¹ - Merge pull request #15 from KSP-KOS/develop
- [x] abenkovskii - SOI documentation
- [x] Dunbaratu - Resolves #40 with new FROM loop syntax.
- [x] Chris Woerz - re-added new vessel structures
- [x] BertCotton - adding comments to .travis.yml
- [x] BertCotton - Adding .travis.yml to allow for builds at https://travis-ci.org/KSP-KOS/KOS Updating the folder hints for the libraries to look in the Resources folder.  The travis.yml will download them into that folder
- [x] abenkovskii - renamed .userprefs
- [x] ÐÐ½Ð´Ñ€ÐµÐ¹ Ð‘ÐµÐ½ÑŒÐºÐ¾Ð²ÑÐºÐ¸Ð¹ - Merge pull request #13 from KSP-KOS/develop
- [x] Chris Woerz - removed userprefs
- [x] Chris Woerz - Merge remote-tracking branch 'abenkovskii/905_fix' into develop
- [x] Chris Woerz - ignore all userprefs
- [x] Chris Woerz - Merge remote-tracking branch 'abenkovskii/body_soi' into develop
- [x] abenkovskii - Fix 905
- [x] ÐÐ½Ð´Ñ€ÐµÐ¹ Ð‘ÐµÐ½ÑŒÐºÐ¾Ð²ÑÐºÐ¸Ð¹ - Merge pull request #12 from KSP-KOS/develop
- [x] Chris Woerz - Merge remote-tracking branch 'abenkovskii/757_fix' into develop
- [x] Chris Woerz - Merge remote-tracking branch 'hvacengi/fix-thrust1.0' into develop
- [x] Chris Woerz - single if statement for casting
- [x] Chris Woerz - Merge remote-tracking branch 'abenkovskii/897_fix' into develop
- [x] abenkovskii - added BODY:SOIRADIUS
- [x] abenkovskii - Now volume index can be float
- [x] abenkovskii - `List files in` now works properly for archive too
- [x] ÐÐ½Ð´Ñ€ÐµÐ¹ Ð‘ÐµÐ½ÑŒÐºÐ¾Ð²ÑÐºÐ¸Ð¹ - Merge pull request #10 from KSP-KOS/develop
- [x] Chris Woerz - review comments
- [x] Chris Woerz - Merge remote-tracking branch 'abenkovskii/float_to_int' into develop
- [x] Chris Woerz - Merge remote-tracking branch 'pgodd/develop' into develop
- [x] Chris Woerz - Merge remote-tracking branch 'hvacengi/update-changelog' into develop
- [x] Chris Woerz - Merge branch 'develop' of github.com:KSP-KOS/KOS into develop
- [x] hvacengi - Add examples of vacuum and sea level.
- [x] hvacengi - Update changelog for my contributions in 0.17.3
- [x] Chris Woerz - Merge pull request #1003 from hvacengi/fix_526
- [x] Brad White - Process electricity in fixed update
- [x] Brad White - Add documentation
- [x] Brad White - Be consistent with floats and doubles
- [x] Brad White - Codemaid cleanup
- [x] Brad White - Continue to update thrust calculations
- [x] ZiwKerman - New IR features docs
- [x] ZiwKerman - Some additions to IR integration.
- [x] Stepan Andreev - Merge pull request #25 from KSP-KOS/develop
- [x] Peter Goddard - remove unnecessary files from parts source
- [x] Chris Woerz - fixed .version file
- [x] Chris Woerz - gitignore work
- [x] Peter Goddard - All part source files for Sketchup, Blender, and Unity
- [x] Peter Goddard - remove files committed in error
- [x] Peter Goddard - All part source files
- [x] Peter Goddard - Fixes #980 sinking into launchpad
- [x] Chris Woerz - Merge pull request #998 from pgodd/develop
- [x] Peter Goddard - New radial computer models
- [x] Chris Woerz - rev versions for release
- [x] Chris Woerz - Update CHANGELOG.md
- [x] abenkovskii - float to int #7: added NaN check
- [x] abenkovskii - float to int #6
- [x] abenkovskii - Save settings
- [x] abenkovskii - float to int #5
- [x] abenkovskii - Fixed window appearing out of screen sometimes
- [x] abenkovskii - Toolbar fix #5
- [x] abenkovskii - Toolbar fix #4
- [x] abenkovskii - Added debug messages
- [x] Chris Woerz - Merge remote-tracking branch 'tdw89/patch-1' into develop
- [x] Chris Woerz - Merge remote-tracking branch 'Dunbaratu/Fixes_971_rename_volume' into develop
- [x] Chris Woerz - Merge remote-tracking branch 'Dunbaratu/Fixes_956_bad_MLFields_for_delegate_relocate_later' into develop
- [x] abenkovskii - This should fix it
- [x] abenkovskii - removed SPACECENTER
- [x] Chris Woerz - Merge remote-tracking branch 'Dunbaratu/Fixes_954_locks_work_in_for' into develop
- [x] Chris Woerz - Merge remote-tracking branch 'Dunbaratu/implement_clearvecdraws' into develop
- [x] Chris Woerz - Merge remote-tracking branch 'Dunbaratu/Fixes_927_meananomalu_now_radians' into develop
- [x] Chris Woerz - Merge remote-tracking branch 'Dunbaratu/Fixes_834' into develop
- [x] abenkovskii - Removed redundant parts
- [x] abenkovskii - Last? change before making a PR
- [x] abenkovskii - It should work now
- [x] abenkovskii - round floats are now integers
- [x] ÐÐ½Ð´Ñ€ÐµÐ¹ Ð‘ÐµÐ½ÑŒÐºÐ¾Ð²ÑÐºÐ¸Ð¹ - Merge pull request #8 from KSP-KOS/develop
- [x] Dunbaratu - Fixes #971 by making rename volume work right.
- [x] Dunbaratu - Fixes #956 - MLFields for OpcodeDelegateRelocateLater was wrong.
- [x] Dunbaratu - Fixes #954 by making locks work in for loop.
- [x] Dunbaratu - Implemented the clearvecdraws command, and left a
- [x] Dunbaratu - Fixes #927 by making mean anomaly into degrees.
- [x] Dunbaratu - Oops - forgot to remove an eraseme debug.
- [x] Dunbaratu - Oops- this line was left from an earlier incorrect attempt at a fix.
- [x] Dunbaratu - Fixes #858 making empty programs have a NOP.
- [x] Chris Woerz - review comments
- [x] Chris Woerz - Merge remote-tracking branch 'hvacengi/fix_952' into develop
- [x] Brad White - Change deprecation exception text on INCOMMRANGE
- [x] Brad White - Fix for #952 setting vector direction set mag to 1
- [x] hvacengi - Forgot to use the new availablethrust in vesselutils
- [x] hvacengi - More work with thrust calculations
- [x] Dunbaratu - documented that nodes only work on active ves.
- [x] Dunbaratu - Fixes #834. protect for null patchedConicSolver
- [x] TDW89 - added new suffixes to docs
- [x] Steven Mading - Merge pull request #950 from ZiwKerman/develop
- [x] hvacengi - Move thrust calc to ModuleEngineAdapter
- [x] ZiwKerman - Add kOS icon to KSC view
- [x] Stepan Andreev - Merge pull request #24 from KSP-KOS/develop
- [x] TDW89 - removed tabs that got pasted in
- [x] TDW89 - added suffexes to PartModule.
- [x] Dwayne Bent - Update and Fix .version file
- [x] Brad White - Fix maxthrust for vessel
- [x] Chris Woerz - Merge remote-tracking branch 'hvacengi/fix_937' into develop
- [x] Chris Woerz - Merge branch 'develop' of github.com:KSP-KOS/KOS into develop
- [x] Steven Mading - Merge pull request #913 from erendrake/target_unset
- [x] Steven Mading - Merge pull request #939 from Dunbaratu/fix_934
- [x] Dunbaratu - Merged in hvacengi's branch that Fixes #934.
- [x] Dunbaratu - Fixes #935 - set by index with suffix term.
- [x] Brad White - Fix #937 vessel:dockingports wrong
- [x] Brad White - Fix for #934 empty return crashes
- [x] Chris Woerz - Merge remote-tracking branch 'hvacengi/core_binding' into Fixes_925_accidental_lowercasing
- [x] Chris Woerz - BREAKING: removed ETA_ and ALT_ bindings
- [x] Chris Woerz - review comments
- [x] Dunbaratu - Fixes #925 and changes how lowercasing gets done.
- [x] hvacengi - Remove reference to waypoint
- [x] hvacengi - Document additional suffixes on vessel and element
- [x] hvacengi - 1st draft documenting the Core part
- [x] Chris Woerz - review comments
- [x] Chris Woerz - Merge remote-tracking branch 'tdw89/patch-1' into develop
- [x] Chris Woerz - review changes
- [x] Chris Woerz - Merge remote-tracking branch 'hvacengi/core_binding' into core_binding
- [x] Chris Woerz - Merge branch 'develop' into core_binding
- [x] TDW89 - adedd version:build
- [x] Brad White - Deprecate INCOMMRANGE
- [x] Brad White - Core version auto-update
- [x] Brad White - Add suffixes to element and vessel
- [x] Brad White - Add Suffixes
- [x] Stepan Andreev - Merge pull request #23 from KSP-KOS/develop
- [x] Chris Woerz - Merge branch 'fixes_914' into develop
- [x] Chris Woerz - mostly spelling
- [x] Chris Woerz - Merge remote-tracking branch 'Dunbaratu/Fixes_923_moved_popscope_to_return' into develop
- [x] Dunbaratu - Fixes #923 by making return capable of popscope.
- [x] ZiwKerman - Proper Handling of AppLauncher Icons
- [x] Stepan Andreev - Merge pull request #22 from KSP-KOS/develop
- [x] Chris Woerz - Merge remote-tracking branch 'ZiwKerman/develop' into develop
- [x] ZiwKerman - Fix attach node for small part
- [x] Brad White - Merge branch 'erendrake/core_binding' into testing-core-binding
- [x] Brad White - Conflict resolution before merging
- [x] Chris Woerz - aggregate resource doesnt cache anymore
- [x] Chris Woerz - set target to empty should always reset
- [x] Chris Woerz - added stub
- [x] Chris Woerz - resurrection
- [x] Chris Woerz - cleanup
- [x] Chris Woerz - retask core to a binding structure
- [x] abenkovskii - Merge pull request #7 from KSP-KOS/develop
