### ISSUE TITLE
kOS v1.1.0 Release Checklist

### ISSUE THREAD

**Issue by hvacengi** [KSP-KOS/KOS#2013]
### Pre-Build
- [x] Update AssemblyInfo for kOS project
- [x] Update AssemblyInfo for kOS.Safe project
- [x] Update AssemblyInfo for kOS.Safe.Test project
- [x] Update `Resources\GameData\kOS\kOS.version`
- [x] Update `doc\source\conf.py`
- [x] Update `CHANGELOG.MD`
- [x] Update `doc\source\changes.rst`

### Build
- [x] Build kOS solution in release mode
- [ ] Run all unit tests
- [x] Ensure that all required resources are in place (module manager)
- [x] Create zip file with a root starting in the `\Resources\` directory
- [x] The zip file should have the GameData folder in the root
- [x] Name the zip file with the following pattern `kOS-v<major>.<minor>.<patch>.zip` (eg kOS-v0.14.2.zip )
- [x] Build the documentation in `\docs\`
- [x] Push the contents of `docs\gh-pages` to the gh-pages branch of KSP-KOS/KOS and verify correct rendering

### Post-Build
- [x] Update master branch from develop branch.
- [x] Build Github release with changelog and title
- [x] Copy Github release to [Curseforge](http://kerbal.curseforge.com/projects/kos-scriptable-autopilot-system?gameCategorySlug=ksp-mods&projectID=220265)
- [x] Copy Github release to [Spacedock](http://spacedock.info/mod/60/kOS:%20Scriptable%20Autopilot%20System)
- [x] Update [Forum thread](http://forum.kerbalspaceprogram.com/index.php?/topic/61827-/) with new change log, release date and version
- [x] Post update in the forum thread
- [x] Post update on [reddit board](http://www.reddit.com/r/kos)
- [x] Push the gh-pages branch to KSP-KOS/KOS_DOC

**Comment by Dunbaratu** [comment]
Everything except the unit tests was done.
I couldn't figure out why Monodevelop refused to do any of the run tests.  As far as I can tell I'm doing everything correctly according to all the documentation, but the tests don't run.  I am hoping that the fact that Travis was okay with it means it ran the unit tests with success.
