### ISSUE TITLE
KSP 0.90 adjustments checklist.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#438]
These are a bullet list of all the KSP 0.90 changes that we expect will affect the mod.

(This should also be split out into a separate issue per bullet point once you work on a thing - if you take one of these to work on, make it a separate issue and start on it.  This is a central list to brainstorm with.)

### new features that 0.90 warrants having:

- [x] Autopilots now have a separate callback hook to use instead of OnFlyByWire.  It supposedly allows manual piloting to override the autopilot piloting.
- [x] Use new SAS pointing spots (orbit prograde, orbit retrorade, surface prograde, surface retrograde, normal, antinormal, radial, antiradial, to target, anti target).
- [x] Space Center Building upgrade system disables some features until the building is up to a certain level.  Should kOS prevent itself from letting scripts use features that the building level disallows, and if so, how can it be done in a way that won't break scripts?  (example, Manuever Nodes require a Tracking Center upgrade). #461
- [x] Ability to query the locations of survey contracts.

### old features that 0.90 broke
- [x] The Applauncher button no longer brings up the control panel in 0.90. #447
- [x] Editor no longer has separate VAB and SPH modes but instead joined them together into one editor mode, with a flag for which kind of editor (this may affect some of how the applauncher button works).
- [x] Fuel lines changed, which probably affects the resource-in-stage parts-walk calculation (while we're at it, maybe look into issue #337 and just gut and re-do the system ).
